language: go

go:
  - 1.2
  - 1.3
  - 1.4
  - tip

install:
  - go get github.com/gorilla/context
  - go get github.com/julienschmidt/httprouter
  - go get github.com/justinas/alice
  - go get github.com/sh4t/community/errs
  - go get github.com/sh4t/community/host
  - go get github.com/sh4t/community/mdw
  - go get github.com/sh4t/community/community-api
  - go get gopkg.in/mgo.v2
  - go get gopkg.in/mgo.v2/bson

script:
  - go test ./...
